# Generated by Django 3.1.7 on 2022-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestopediaTerms',
            fields=[
                ('termID', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=300)),
                ('definition', models.TextField()),
            ],
            options={
                'db_table': 'Investopedia_Term',
                'managed': True,
            },
        ),
    ]
